# Generated by Django 2.0.1 on 2018-02-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_redux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='socio_auth_avatar',
            field=models.URLField(blank=True, default='https://www.gravatar.com/avatar/4309fdf1236a9cf2cd87f90a87cee8a9?d=mm&s=256', max_length=400),
        ),
    ]
