# Generated by Django 2.0.1 on 2018-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_redux', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=50),
        ),
    ]
