# Generated by Django 2.0.1 on 2018-03-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_avatar',
            field=models.ImageField(default='static/images/class_cover.jpg', upload_to='class_image'),
        ),
    ]
