# Generated by Django 2.0 on 2018-02-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
