# Generated by Django 2.0.1 on 2018-02-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.FileField(blank=True, upload_to='question_files'),
        ),
        migrations.AlterField(
            model_name='question',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='forum.Class'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='question_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='question_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
