# Generated by Django 2.0.1 on 2018-02-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
