# Generated by Django 2.0.1 on 2018-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180310_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_avatar',
            field=models.ImageField(default='media/class_image/class_cover.jpg', upload_to='class_image'),
        ),
    ]
