# Generated by Django 2.0 on 2018-02-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20180206_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='files',
            field=models.FileField(blank=True, upload_to='answer_files'),
        ),
    ]
