# Generated by Django 2.0 on 2018-02-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_answer_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='answer_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='forum.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='answer_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
